" Specify a directory for plugins
" - For Neovim: ~/.local/share/nvim/plugged
" - Avoid using standard Vim directory names like 'plugin'
call plug#begin('~/.vim/plugged')

Plug 'altercation/vim-colors-solarized'
Plug 'lifepillar/vim-mucomplete'
Plug 'autozimu/LanguageClient-neovim', {
    \ 'branch': 'next',
    \ 'do': 'bash install.sh',
    \ }
Plug 'rust-lang/rust.vim'
Plug 'tikhomirov/vim-glsl'
Plug 'lervag/vimtex'
Plug 'KeitaNakamura/tex-conceal.vim', {'for': 'tex'}
Plug 'dense-analysis/ale'

" Initialize plugin system
call plug#end()

"""" 1. Vim Behaviour.
" Use filetype-based syntax highlighting, ftplugins, and indentation.
syntax enable
filetype plugin indent on

" Use numbering. Don't use relative numbering as this is slow (especially in
" .tex files).
set number

" Enables mouse support. Note that on Mac OS X this doesn't work well on the
" default terminal.
set mouse=a
if has("mouse_sgr")
    set ttymouse=sgr
else
    set ttymouse=xterm2
end

set backspace=2 " make backspace work like most other apps

set clipboard=unnamedplus " use system clipboard

" mucomplete/omnicomplete
set completeopt+=menuone,noselect
set completeopt-=preview

"""" 2. Key Bindings.
" More convenient movement when lines are wrapped.
nmap j gj
nmap k gk

inoremap jk <ESC>

let mapleader="\<Space>"
let maplocalleader="\<Space>"

" Turn off highlighting for search and Merlin (OCaml) with <CR>.
"nnoremap <CR> :nohlsearch <bar> redraw! <CR>
nnoremap <CR> :nohlsearch <bar> redraw! <bar> :MerlinClearEnclosing <CR>

nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" better moving between buffers
nnoremap ]b :bn <CR>
nnoremap [b :bp <CR>

"""" 3. Vim Appearance.
set background=dark
let g:solarized_termcolors=16
colorscheme solarized
" Search settings
set hlsearch " highlight
set incsearch " jump to best fit

" Tab settings
set autoindent
set smartindent
set tabstop=2
set shiftwidth=2
set expandtab
" Make statusline appear even with only single window.
set laststatus=2

set splitbelow
set splitright

set timeoutlen=1000 ttimeoutlen=0

" Show vertical line at column 80
set colorcolumn=80

" Highlight trailing whitespace
" (https://vim.fandom.com/wiki/Highlight_unwanted_spaces)
highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/
autocmd BufWinEnter * match ExtraWhitespace /\s\+$/
autocmd InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/
autocmd InsertLeave * match ExtraWhitespace /\s\+$/
autocmd BufWinLeave * call clearmatches()

let g:ale_linters = {
      \   'ocaml': ['merlin'],
      \}

"""" 4. Language specific.
autocmd Filetype rust setlocal ts=4 sw=4 expandtab
let g:rustfmt_autosave = 1
set hidden
let g:LanguageClient_serverCommands = {
      \ 'rust': ['rustup', 'run', 'stable', 'rls'],
      \ }
nnoremap <F5> :call LanguageClient_contextMenu()<CR>
" Or map each action separately
nnoremap <silent> K :call LanguageClient#textDocument_hover()<CR>
nnoremap <silent> gd :call LanguageClient#textDocument_definition()<CR>
nnoremap <silent> <F2> :call LanguageClient#textDocument_rename()<CR>

let g:tex_flavor='latex'
let g:vimtex_quickfix_mode=0
set conceallevel=1
let g:tex_conceal='abdmg'
" ## added by OPAM user-setup for vim / base ## 93ee63e278bdfc07d1139a748ed3fff2 ## you can edit, but keep this line
let s:opam_share_dir = system("opam config var share")
let s:opam_share_dir = substitute(s:opam_share_dir, '[\r\n]*$', '', '')

let s:opam_configuration = {}

function! OpamConfOcpIndent()
  execute "set rtp^=" . s:opam_share_dir . "/ocp-indent/vim"
endfunction
let s:opam_configuration['ocp-indent'] = function('OpamConfOcpIndent')

function! OpamConfOcpIndex()
  execute "set rtp+=" . s:opam_share_dir . "/ocp-index/vim"
endfunction
let s:opam_configuration['ocp-index'] = function('OpamConfOcpIndex')

function! OpamConfMerlin()
  let l:dir = s:opam_share_dir . "/merlin/vim"
  execute "set rtp+=" . l:dir
endfunction
let s:opam_configuration['merlin'] = function('OpamConfMerlin')

let s:opam_packages = ["ocp-indent", "ocp-index", "merlin"]
let s:opam_check_cmdline = ["opam list --installed --short --safe --color=never"] + s:opam_packages
let s:opam_available_tools = split(system(join(s:opam_check_cmdline)))
for tool in s:opam_packages
  " Respect package order (merlin should be after ocp-index)
  if count(s:opam_available_tools, tool) > 0
    call s:opam_configuration[tool]()
  endif
endfor
" ## end of OPAM user-setup addition for vim / base ## keep this line
" ## added by OPAM user-setup for vim / ocp-indent ## f869f9a082cfea5ea02061eaa32326cd ## you can edit, but keep this line
if count(s:opam_available_tools,"ocp-indent") == 0
  source "/home/marc/.opam/4.06.0/share/ocp-indent/vim/indent/ocaml.vim"
endif
" ## end of OPAM user-setup addition for vim / ocp-indent ## keep this line
